### ISSUE TITLE
Add Sudoku Exception with Message for the failure

### ISSUE THREAD

**Issue by Nickleaton** [Nickleaton/sudoku#232]
Traceback (most recent call last):
  File "C:\Users\nickl\AppData\Local\Programs\Python\Python311\Lib\unittest\case.py", line 57, in testPartExecutor
    yield
  File "C:\Users\nickl\AppData\Local\Programs\Python\Python311\Lib\unittest\case.py", line 623, in run
    self._callTestMethod(testMethod)
  File "C:\Users\nickl\AppData\Local\Programs\Python\Python311\Lib\unittest\case.py", line 579, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "C:\Users\nickl\PycharmProjects\sudoku\tests\acceptance\acceptance_test.py", line 86, in test_all
    command.execute()
  File "C:\Users\nickl\PycharmProjects\sudoku\src\commands\composed_command.py", line 25, in execute
    item.execute()
  File "C:\Users\nickl\PycharmProjects\sudoku\src\commands\create_problem_command.py", line 19, in execute
    self.problem = Item.create(self.parent.board.board, {'Constraints': self.parent.config.config['Constraints']})
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nickl\PycharmProjects\sudoku\src\items\item.py", line 86, in create
    return clazz.create(board, yaml)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nickl\PycharmProjects\sudoku\src\items\constraints.py", line 24, in create
    result.add(Item.create(board, constraint))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nickl\PycharmProjects\sudoku\src\items\item.py", line 83, in create
    raise Exception

**Comment by Nickleaton** [comment]
Currently Logging when not a valid Constraint name
